### ISSUE TITLE
Error on npm run watch

### ISSUE THREAD

**Issue by anthonybrown** [learn-javascript-courses/composition-examples#1]
Hi Eric, I just cloned the repo and followed the steps. When I run the `npm run watch` command, I'm presented with this error message:

> module.js:440
    throw err;
    ^

> Error: Cannot find module 'eslint-plugin-react'
>     at Function.Module._resolveFilename (module.js:438:15)
>     at Function.Module._load (module.js:386:25)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at /Users/tonybrown/Documents/Development/JavaScript_Projects/EricElliot/composition-examples/node_modules/eslint/lib/cli-engine.js:125:26
>     at Array.forEach (native)
>     at loadPlugins (/Users/tonybrown/Documents/Development/JavaScript_Projects/EricElliot/composition-examples/node_modules/eslint/lib/cli-engine.js:116:21)
>     at processText (/Users/tonybrown/Documents/Development/JavaScript_Projects/EricElliot/composition-examples/node_modules/eslint/lib/cli-engine.js:204:5)
>     at processFile (/Users/tonybrown/Documents/Development/JavaScript_Projects/EricElliot/composition-examples/node_modules/eslint/lib/cli-engine.js:270:18)
> 

Here is a link to my [npm error
log](https://gist.github.com/anthonybrown/4500012f0af1cb3f93357321a58b39e9)

**Comment by anthonybrown** [comment]
I see there was a typo in the `package.json` file. 
I missed that, I read through that file a few times and missed that.

**Comment by ericelliott** [comment]
Glad you figured out the problem with your global `.eslintrc` file.

**Comment by anthonybrown** [comment]
Yeah, that was a head scratcher for sure lol.
I'm using yours now for my global inside my dev env, I changed a few things but
basically everything is hunky dory 👍

**Comment by ericelliott** [comment]
I don't have a global .eslintrc file. =)
